# Generated by Django 2.2.7 on 2020-02-27 10:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('converter', '0002_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='history',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='history',
            name='sportname',
        ),
        migrations.RemoveField(
            model_name='history',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='feedmessages',
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('date', models.CharField(max_length=64)),
                ('location', models.CharField(choices=[('universum', 'Universum'), ('asc', 'ASC'), ('amstel', 'Amstelcampus'), ('crea', 'CREA'), ('clubwest', 'ClubWest')], default='universum', max_length=64)),
                ('participants', models.ManyToManyField(related_name='participants', to='converter.Profile')),
                ('rating', models.ManyToManyField(related_name='ratings', to='converter.Rating')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
