# Generated by Django 2.2.7 on 2020-02-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20200227_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='end',
            field=models.CharField(default='17', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='start',
            field=models.CharField(default='18', max_length=64),
            preserve_default=False,
        ),
    ]
