# Generated by Django 2.2.7 on 2020-02-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_auto_20200227_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='date',
        ),
    ]
