# Generated by Django 2.2.7 on 2020-02-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_auto_20200227_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='event_id',
            field=models.IntegerField(default=0),
        ),
    ]
