# Generated by Django 2.2.7 on 2020-02-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_rating_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.CharField(default='Super leuk!!!!!', max_length=300),
            preserve_default=False,
        ),
    ]
