# Generated by Django 2.2.10 on 2020-02-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0007_rating_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='converter.ScheduleItem'),
        ),
    ]
