# Generated by Django 2.2.7 on 2020-02-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0008_auto_20200228_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='date',
            field=models.CharField(default='28 February', max_length=64),
            preserve_default=False,
        ),
    ]
