# Generated by Django 2.2.7 on 2020-03-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0009_scheduleitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='images/logo.png', upload_to='images'),
        ),
    ]
