# Generated by Django 2.2.7 on 2020-03-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0010_auto_20200312_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='hearts',
            field=models.IntegerField(default=0),
        ),
    ]
