# Generated by Django 2.2.7 on 2020-03-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0011_scheduleitem_hearts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
